Fix error with rspec tests
Running tests that used capybara was causing a NoMethodError: 'undefined method '[]' for nil:NilClass' which was fixed by renaming the *.css files to *.scss. Now all tests run without failures.

+ Updated gems